# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Backprop (Internal)
#'
#' @param n_hidden Hidden layer numbers.
#' @param w_ini Initial weights.
#' @param load_param Whether to load parameters.
#' @param weight Weights.
#' @param bias Biases.
#' @param x Training.
#' @param y Training.
#' @param w Training.
#' @param valid Whether to use a validation set.
#' @param x_valid Validation.
#' @param y_valid Validation.
#' @param w_valid Validation.
#' @param activ Activation function.
#' @param n_epoch Number of epochs.
#' @param n_batch Batch size.
#' @param model_type Model type.
#' @param learning_rate (Initial) learning rate.
#' @param l1_reg L1-penalty.
#' @param l2_reg L2-penalty.
#' @param early_stop Whether to early stop.
#' @param early_stop_det Number of epochs to determine early-stop.
#' @param learning_rate_adaptive Adaptive learning rate adjustment method.
#' @param rho Parameter.
#' @param epsilon Parameter.
#' @param beta1 Parameter.
#' @param beta2 Parameter.
#' @param loss_f Loss function.
#'
#' @return A list of outputs
#'
backprop <- function(n_hidden, w_ini, load_param, weight, bias, x, y, w, valid, x_valid, y_valid, w_valid, activ, n_epoch, n_batch, model_type, learning_rate, l1_reg, l2_reg, early_stop, early_stop_det, learning_rate_adaptive, rho, epsilon, beta1, beta2, loss_f) {
    .Call(`_fsDNN_backprop`, n_hidden, w_ini, load_param, weight, bias, x, y, w, valid, x_valid, y_valid, w_valid, activ, n_epoch, n_batch, model_type, learning_rate, l1_reg, l2_reg, early_stop, early_stop_det, learning_rate_adaptive, rho, epsilon, beta1, beta2, loss_f)
}

